#!/usr/bin/env python3
"""
Download a servo-calibration CSV from the roboRIO, fit a degree-2
polynomial map (forward and inverse), show error visualisation, and
write the result to config/servo_calibration_map.py.

Usage:
    python scripts/download_calibration.py [roborio-host]
"""

import argparse
import csv
import os
import subprocess
import sys
import tempfile
import textwrap
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

_FEATURE_NAMES = ["1", "r", "p", "y", "r²", "p²", "y²", "r·p", "r·y", "p·y"]


def _make_features(R: np.ndarray, P: np.ndarray, Y: np.ndarray) -> np.ndarray:
    ones = np.ones_like(R)
    return np.column_stack([ones, R, P, Y, R**2, P**2, Y**2, R * P, R * Y, P * Y])


def _fit(X: np.ndarray, y: np.ndarray) -> tuple[np.ndarray, float, np.ndarray]:
    coeffs, *_ = np.linalg.lstsq(X, y, rcond=None)
    pred = X @ coeffs
    resid = y - pred
    rms = float(np.sqrt(np.mean(resid**2)))
    return coeffs, rms, pred


def _invert_rotation(r: np.ndarray) -> np.ndarray:
    """Invert a rotation matrix (for sensor-to-bench frame)."""
    return r.T


def list_remote_files(host: str, remote_dir: str) -> list[str]:
    result = subprocess.run(
        ["ssh", f"lvuser@{host}", "ls", "-1", remote_dir],
        capture_output=True,
        text=True,
        timeout=10,
    )
    if result.returncode != 0:
        print(f"Error listing remote files: {result.stderr.strip()}")
        sys.exit(1)
    lines = [line.strip() for line in result.stdout.strip().split("\n") if line.strip()]
    return [os.path.join(remote_dir, line) for line in lines]


def download_file(host: str, remote_path: str, local_path: str) -> None:
    subprocess.run(
        ["scp", f"lvuser@{host}:{remote_path}", local_path],
        check=True,
        timeout=30,
    )


def load_csv(path: str) -> tuple[dict[str, np.ndarray], dict[str, str]]:
    """Return (column_data, metadata) where metadata is parsed from # comments."""
    meta: dict[str, str] = {}
    data_rows: list[str] = []
    with open(path, newline="") as f:
        for line in f:
            if line.startswith("#"):
                if ":" in line:
                    key, _, val = line.lstrip("#").strip().partition(":")
                    meta[key.strip()] = val.strip()
            else:
                data_rows.append(line)
    reader = csv.DictReader(data_rows)
    rows = list(reader)
    data = {k: np.array([float(r[k]) for r in rows]) for k in rows[0].keys()}
    return data, meta


def plot_results(
    data: dict[str, np.ndarray],
    pred_r: np.ndarray,
    pred_p: np.ndarray,
    pred_y: np.ndarray,
    rms_r: float,
    rms_p: float,
    rms_y: float,
    out_path: str,
) -> None:
    fig, axes = plt.subplots(3, 2, figsize=(14, 10))
    fig.suptitle("Servo Calibration — Polynomial Fit (degree 2, cross terms)")

    labels = [
        ("Roll", "actual_roll_rad", pred_r, rms_r),
        ("Pitch", "actual_pitch_rad", pred_p, rms_p),
        ("Yaw", "actual_yaw_rad", pred_y, rms_y),
    ]

    for i, (name, actual_key, pred, rms) in enumerate(labels):
        actual = data[actual_key]
        resid = actual - pred

        ax_scatter = axes[i, 0]
        ax_scatter.scatter(actual, pred, s=8, alpha=0.6)
        lim = [min(actual.min(), pred.min()), max(actual.max(), pred.max())]
        ax_scatter.plot(lim, lim, "r--", lw=1)
        ax_scatter.set_xlabel(f"Actual {name} (rad)")
        ax_scatter.set_ylabel(f"Predicted {name} (rad)")
        ax_scatter.set_title(f"{name} — RMS {rms:.4f} rad")
        ax_scatter.grid(True, alpha=0.3)

        ax_hist = axes[i, 1]
        ax_hist.hist(resid, bins=30, alpha=0.7)
        ax_hist.set_xlabel(f"{name} Residual (rad)")
        ax_hist.set_ylabel("Count")
        ax_hist.set_title(f"{name} Residual Distribution")
        ax_hist.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(out_path, dpi=150)
    print(f"Plot saved to {out_path}")


def generate_map_code(
    coeffs_r: np.ndarray,
    coeffs_p: np.ndarray,
    coeffs_y: np.ndarray,
    inv_coeffs_r: np.ndarray,
    inv_coeffs_p: np.ndarray,
    inv_coeffs_y: np.ndarray,
    rms_r: float,
    rms_p: float,
    rms_y: float,
    n_points: int,
    avg_gain: float,
    source_file: str = "<unknown>",
    roborio_serial: str = "<unknown>",
) -> str:
    now = __import__("datetime").datetime.now().strftime("%Y-%m-%d %H:%M")
    host = __import__("socket").gethostname()

    def fmt_list(arr: np.ndarray) -> str:
        vals = ", ".join(f"{v:.10f}" for v in arr)
        return f"[{vals}]"

    return textwrap.dedent(f'''\
    """
    Generated by scripts/download_calibration.py — do not edit manually.

    Last updated:  {now}
    Source CSV:    {source_file}
    RoboRIO serial:{roborio_serial}
    Generated on:  {host}
    """


    def _predict(features: list[float], coeffs: list[float]) -> float:
        return sum(c * f for c, f in zip(coeffs, features))


    def _make_features(
        r: float, p: float, y: float
    ) -> list[float]:
        return [1.0, r, p, y, r * r, p * p, y * y, r * p, r * y, p * y]


    class CalibrationMap:
        FORWARD_COEFFS_ROLL = {fmt_list(coeffs_r)}
        FORWARD_COEFFS_PITCH = {fmt_list(coeffs_p)}
        FORWARD_COEFFS_YAW = {fmt_list(coeffs_y)}

        INVERSE_COEFFS_SERVO_R = {fmt_list(inv_coeffs_r)}
        INVERSE_COEFFS_SERVO_P = {fmt_list(inv_coeffs_p)}
        INVERSE_COEFFS_SERVO_Y = {fmt_list(inv_coeffs_y)}

        AVG_GAIN_RAD_PER_SERVO = {avg_gain:.6f}

        N_POINTS = {n_points}
        RMS_ERROR_ROLL = {rms_r:.8f}
        RMS_ERROR_PITCH = {rms_p:.8f}
        RMS_ERROR_YAW = {rms_y:.8f}

        @classmethod
        def forward(
            cls, servo_r: float, servo_p: float, servo_y: float
        ) -> tuple[float, float, float]:
            feats = _make_features(servo_r, servo_p, servo_y)
            return (
                _predict(feats, cls.FORWARD_COEFFS_ROLL),
                _predict(feats, cls.FORWARD_COEFFS_PITCH),
                _predict(feats, cls.FORWARD_COEFFS_YAW),
            )

        @classmethod
        def inverse(
            cls, roll_rad: float, pitch_rad: float, yaw_rad: float
        ) -> tuple[float, float, float]:
            feats = _make_features(roll_rad, pitch_rad, yaw_rad)
            return (
                _predict(feats, cls.INVERSE_COEFFS_SERVO_R),
                _predict(feats, cls.INVERSE_COEFFS_SERVO_P),
                _predict(feats, cls.INVERSE_COEFFS_SERVO_Y),
            )
    ''')


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "host",
        nargs="?",
        default="roborio-6708-frc.local",
        help="roboRIO hostname or IP",
    )
    parser.add_argument(
        "--remote-dir",
        default="/home/lvuser/calibration_data",
        help="remote directory with CSV files",
    )
    args = parser.parse_args()

    print(f"Listing CSV files on {args.host}:{args.remote_dir} ...")
    remote_files = list_remote_files(args.host, args.remote_dir)
    csv_files = [fn for fn in remote_files if fn.endswith(".csv")]
    if not csv_files:
        print("No CSV files found.")
        sys.exit(1)

    print("Available calibration files:")
    for i, fn in enumerate(csv_files):
        print(f"  [{i}] {fn}")
    choice = int(input("Select file #: "))
    if choice < 0 or choice >= len(csv_files):
        print("Invalid selection.")
        sys.exit(1)
    remote_path = csv_files[choice]

    with tempfile.TemporaryDirectory() as tmpdir:
        local_path = os.path.join(tmpdir, "calib.csv")
        print(f"Downloading {remote_path} ...")
        download_file(args.host, remote_path, local_path)

        data, meta = load_csv(local_path)
    n_points = len(next(iter(data.values())))
    print(f"Loaded {n_points} data points.")

    R, P, Y = data["servo_roll"], data["servo_pitch"], data["servo_yaw"]
    AR, AP, AY = (
        data["actual_roll_rad"],
        data["actual_pitch_rad"],
        data["actual_yaw_rad"],
    )

    X_servo = _make_features(R, P, Y)

    coeffs_r, rms_r, pred_r = _fit(X_servo, AR)
    coeffs_p, rms_p, pred_p = _fit(X_servo, AP)
    coeffs_y, rms_y, pred_y = _fit(X_servo, AY)

    X_angle = _make_features(AR, AP, AY)
    inv_cr, inv_rms_r, _ = _fit(X_angle, R)
    inv_cp, inv_rms_p, _ = _fit(X_angle, P)
    inv_cy, inv_rms_y, _ = _fit(X_angle, Y)

    avg_gain = float(np.mean(np.abs(AR - AP + AY) / (np.abs(R + P + Y) + 1e-8)))

    print("\n=== Forward map (servo → angle) ===")
    print(f"  Roll RMS:  {rms_r:.6f} rad")
    print(f"  Pitch RMS: {rms_p:.6f} rad")
    print(f"  Yaw RMS:   {rms_y:.6f} rad")
    print("\n=== Inverse map (angle → servo) ===")
    print(f"  Roll RMS:  {inv_rms_r:.6f} servo units")
    print(f"  Pitch RMS: {inv_rms_p:.6f} servo units")
    print(f"  Yaw RMS:   {inv_rms_y:.6f} servo units")

    plot_path = os.path.join(os.path.dirname(__file__) or ".", "calibration_fit.png")
    plot_results(data, pred_r, pred_p, pred_y, rms_r, rms_p, rms_y, plot_path)

    print(f"\nAverage gain: {avg_gain:.4f} rad/servo-unit")

    approved = input("\nWrite config/servo_calibration_map.py? [y/N] ")
    if approved.strip().lower() != "y":
        print("Aborted.")
        sys.exit(0)

    repo_root = Path(__file__).resolve().parent.parent
    out_path = repo_root / "config" / "servo_calibration_map.py"
    source_name = os.path.basename(remote_path)
    roborio_serial = meta.get("roboRIO serial", "<unknown>")
    code = generate_map_code(
        coeffs_r,
        coeffs_p,
        coeffs_y,
        inv_cr,
        inv_cp,
        inv_cy,
        rms_r,
        rms_p,
        rms_y,
        n_points,
        avg_gain,
        source_file=source_name,
        roborio_serial=roborio_serial,
    )
    with open(out_path, "w") as f:
        f.write(code)
    print(f"Written to {out_path}")


if __name__ == "__main__":
    main()
